
## Title for your Home Page
home_title = '''Hotlink Archive Template'''

# Set the caption for each folder's index page
caption_dict = {
    "Hotlink Archive Template": "edit this home page caption",
    "fan-stuff": "make sure to match the folder names when writing these captions",
    "rename1": "not too hard!"
}



## -------- EXCLUSIONS ----------

## folders you want to exclude from indexing
exclude_dir = {'.git','.github', 'extra-folder'}
	## DO NOT remove .git or .github from this exclusion list, or bad things will happen

## files you want to exclude from indexing
exclude_file = {'create-index.py','index.html','create-index.exe'}


import os

def write_index(root_dir):
    index_file = "index.html"
    f_template = '''<tr><td><a href="{name}">{name}</a></td></tr>'''

    for dir_path, dirs, files in os.walk(root_dir):
        
		## index file path
        index_path = os.path.join(dir_path, index_file)
        
        title = os.path.basename(dir_path)
        if title == '.': title = home_title
        
        caption = [str(caption_dict.get(title,''))]


        dirs[:] = [d for d in dirs if d not in exclude_dir]
        files[:] = [f for f in files if f not in exclude_file]


        with open(index_path, "w") as out:
            
			## Write the header
            out.write( title.join( HEADERS ) )
            
			## Write the page caption if available
            out.write( "<p>" + title.join(caption) + "</p>")
   
            ## Write the Table
            out.write( title.join( TABLE1 ) )
            for name in files:                
                out.write(f_template.format(name=name) + "\n")
            for name in dirs:                
                out.write(f_template.format(name=name) + "\n")
            out.write( title.join( TABLE2 ) )
            
			## add HOME button to subfolders
            if not title == home_title: out.write( title.join( HOME ) )
			
			## write footer
            out.write( title.join( FOOTER ) )
                
HOME = ['''
		<br>
        <p>
        Insert a HOME Button vvvv Replace the URL with your Home Page vvvvv
        </p>
        <p><strong>
		<a href="https://hotlink-archive-template.pages.dev/">Home</a>
		</strong></p>
        ''']

HEADERS = ['''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="Author" content="Generated by index.html.py @ https://gist.github.com/yig/e59eaa22f5042320ecf18a87da4e44ae">
<title>''', '''</title>
<!-- <link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css"> -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css"> -->
<!-- <link rel="stylesheet" href="fonts/Inter/inter.css"> -->
<!-- <link rel="stylesheet" href="new.css"> -->

<style type="text/css">
:root {
	--nc-font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
	--nc-font-mono: Consolas, monaco, 'Ubuntu Mono', 'Liberation Mono', 'Courier New', Courier, monospace;

	/* Light theme */
	--nc-tx-1: #000000;
	--nc-tx-2: #1A1A1A;
	--nc-bg-1: #FFFFFF;
	--nc-bg-2: #F6F8FA;
	--nc-bg-3: #E5E7EB;
	--nc-lk-1: #0070F3;
	--nc-lk-2: #0366D6;
	--nc-lk-tx: #FFFFFF;
	--nc-ac-1: #79FFE1;
	--nc-ac-tx: #0C4047;

	/* Dark theme */
	--nc-d-tx-1: #ffffff;
	--nc-d-tx-2: #eeeeee;
	--nc-d-bg-1: #000000;
	--nc-d-bg-2: #111111;
	--nc-d-bg-3: #222222;
	--nc-d-lk-1: #3291FF;
	--nc-d-lk-2: #0070F3;
	--nc-d-lk-tx: #FFFFFF;
	--nc-d-ac-1: #7928CA;
	--nc-d-ac-tx: #FFFFFF;
}

@media (prefers-color-scheme: dark) {
	:root {
		--nc-tx-1: var(--nc-d-tx-1);
		--nc-tx-2: var(--nc-d-tx-2);
		--nc-bg-1: var(--nc-d-bg-1);
		--nc-bg-2: var(--nc-d-bg-2);
		--nc-bg-3: var(--nc-d-bg-3);
		--nc-lk-1: var(--nc-d-lk-1);
		--nc-lk-2: var(--nc-d-lk-2);
		--nc-lk-tx: var(--nc--dlk-tx);
		--nc-ac-1: var(--nc-d-ac-1);
		--nc-ac-tx: var(--nc--dac-tx);
	}
}

* {
	/* Reset margins and padding */
	margin: 0;
	padding: 0;
}


ol,
p,
table,
textarea,
ul,
video {
	/* Margins for most elements */
	margin-bottom: 1rem;
}

html,input,select,button {
	/* Set body font family and some finicky elements */
	font-family: var(--nc-font-sans);
}

body {
	/* Center body in page */
	margin: 0 auto;
	max-width: 600px;
	padding: 2rem;
	border-radius: 6px;
	overflow-x: hidden;
	word-break: break-word;
	overflow-wrap: break-word;
	background: var(--nc-bg-1);

	/* Main body text */
	color: var(--nc-tx-2);
	font-size: 1.03rem;
	line-height: 1.5;
}

::selection {
	/* Set background color for selected text */
	background: var(--nc-ac-1);
	color: var(--nc-ac-tx);
}

h1,h2,h3,h4,h5,h6 {
	line-height: 1;
	color: var(--nc-tx-1);
	padding-top: .875rem;
}

h1,
h2,
h3 {
	color: var(--nc-tx-1);
	padding-bottom: 2px;
	margin-bottom: 8px;
	border-bottom: 1px solid var(--nc-bg-2);
}

h4,
h5,
h6 {
	margin-bottom: .3rem;
}

h1 {
	font-size: 2.25rem;
}

h2 {
	font-size: 1.85rem;
}

h3 {
	font-size: 1.55rem;
}

h4 {
	font-size: 1.25rem;
}

a {
	color: var(--nc-lk-1);
}

a:hover {
	color: var(--nc-lk-2);
}


header {
	background: var(--nc-bg-2);
	border-bottom: 1px solid var(--nc-bg-3);
	padding: 2rem 1.5rem;
	
	/* This sets the right and left margins to cancel out the body's margins. It's width is still the same, but the background stretches across the page's width. */

	margin-top: -2rem;
	margin-bottom: 2rem;

	margin-left: calc(0px - (50vw - 50%));
	margin-right: calc(0px - (50vw - 50%));
	
	padding-left: calc(50vw - 50%);
	padding-right: calc(50vw - 50%);
}

header h1,
header h2,
header h3 {
	padding-bottom: 0;
	border-bottom: 0;
}

header > *:first-child {
	margin-top: 0;
	padding-top: 0;
}

header > *:last-child {
	margin-bottom: 0;
}

hr {
	/* Reset the border of the <hr> separator, then set a better line */
	border: 0;
	border-bottom: 1px solid var(--nc-bg-3);
	margin: 1rem auto;
}


table {
	/* border-collapse sets the table's elements to share borders, rather than floating as separate "boxes". */
	border-collapse: collapse;
	width: 100%;
}

td,
th {
	border: 1px solid var(--nc-bg-3);
	text-align: left;
	padding: .5rem;
}

th {
	background: var(--nc-bg-2);
}

tr:nth-child(even) {
	/* Set every other cell slightly darker. Improves readability. */
	background: var(--nc-bg-2);
}

table caption {
	font-weight: bold;
	margin-bottom: .5rem;
}

textarea {
	/* Don't let the <textarea> extend off the screen naturally or when dragged by the user */
	max-width: 100%;
}

ol,
ul {
	/* Replace the browser default padding */
	padding-left: 2rem;
}

li {
	margin-top: .4rem;
}

ul ul,
ol ul,
ul ol,
ol ol {
	margin-bottom: 0;
}


</style>
</head>
<body>
<header><h1 class="title">''', '''</h1></header>
''']

TABLE1 = ['''
          <table>
          ''']

TABLE2 = ['''
          </table>
          ''']


FOOTER = ['''
          </body>
          </html>
          ''']


WEB_ROOT = "."
write_index(WEB_ROOT)
